name: deploy-shop

on:
  push:
    branches:
      - master
    paths:
      - "shop/**"

  workflow_dispatch:

defaults:
  run:
    working-directory: shop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install

      - uses: actions/checkout@v2
      - run: npm run build

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: AWS S3
        run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/shop/latest

      - name: AWS CloudFront
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} --paths '/shop/latest/remoteEntry.js'
